# Generated by Django 4.2.7 on 2023-11-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=100)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'DRAFT'), (2, 'PUBLISHED'), (3, 'REMOVED')], default=1)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
