# Generated by Django 4.2.7 on 2023-12-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticuloApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'DRAFT'), ('2', 'PUBLISHED'), ('3', 'REMOVED')], default='DRAFT', max_length=10),
        ),
    ]
