# Generated by Django 4.2.7 on 2023-11-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticuloApp', '0002_category_comment_alter_post_slug_postcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('1', 'celeste'), ('2', 'beige'), ('3', 'salmon')], default='celeste', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(choices=[('1', 'nacional'), ('2', 'provincial'), ('3', 'municipal')], default='nacional'),
        ),
    ]
